name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.0
  flutter_blue_plus: ^1.35.0
  flutter_riverpod: ^3.2.0
  flutter_webrtc: ^1.2.1
  google_fonts: ^6.1.0
  http: ^1.6.0
  image: ^4.1.3
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  sqflite: ^2.3.2
  video_player: ^2.8.6
  web_socket_channel: ^3.0.3
  camerawesome: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - static/walking.mp4
    - assets/img/

flutter_native_splash:
  # Required: Set a background color (hex format) or use background_image
  color: "#FFFFFF" 
  # Optional: Specify an image asset
  image: assets/img/splash.png
  # Optional: Set to true if you want a fullscreen splash screen
  # fullscreen: true

  # Optional: Android 12+ specific configuration (see package docs for details)
  # android_12:
  #   image: assets/images/splash_logo_android12.png
  #   color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  # For Android Adaptive Icons (Optional but recommended)
  adaptive_icon_background: "#ffffff" # or image path
  adaptive_icon_foreground: "assets/img/icon.png"